export const albums = [
  {
    name: 'The College Dropout',
    id: '1',
    img: '/src/albums/the college dropout.jpg',
    stars: '',
    review: '',
  },
  {
    name: 'Late Registration',
    id: '2',
    img: '/src/albums/late registration.jpg',
    stars: '',
    review: '',
  },
  { name: 'Graduation', id: '3', img: '/src/albums/graduation.jpg', stars: '', review: '' },
  {
    name: '808s & Heartbreak',
    id: '4',
    img: '/src/albums/808s and heartbreak.webp',
    stars: '',
    review: '',
  },
  {
    name: 'Watch the Throne',
    id: '5',
    img: '/src/albums/watch the throne.jpg',
    stars: '',
    review: '',
  },
  { name: 'MBDTF', id: '6', img: '/src/albums/mbdtf.jpg', stars: '', review: '' },
  {
    name: 'The Life of Pablo',
    id: '7',
    img: '/src/albums/the life of pablo.jpg',
    stars: '',
    review: '',
  },
  { name: 'Ye', id: '8', img: '/src/albums/ye.jpg', stars: '', review: '' },
  {
    name: 'Kids See Ghosts',
    id: '9',
    img: '/src/albums/kids see ghosts.png',
    stars: '',
    review: '',
  },
  { name: 'Jesus is King', id: '10', img: '/src/albums/jesus is king.png', stars: '', review: '' },
  { name: 'Donda', id: '11', img: '/src/albums/donda.jpg', stars: '', review: '' },
  { name: 'Vultures 1', id: '12', img: '/src/albums/vultures 1.webp', stars: '', review: '' },
  { name: 'Vultures 2', id: '13', img: '/src/albums/vultures 2.png', stars: '', review: '' },
]
